import { useState, memo, useMemo, useEffect } from "react";
import { User, Bot, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type {
  Message,
  Attachment,
  QuestionInfo,
  QuestionAnswerEntry,
} from "../types";
import { QuestionCard } from "./QuestionCard";
import { ToolCallCard } from "./ToolCallCard";
import type { ToolCallDisplay } from "./ToolCallCard";

const API_BASE = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";

// Origins from which we will render image attachments inline. Anything outside
// this allowlist is shown as a placeholder with the raw URL as text — without
// the gate, a tool result containing `https://attacker.example/img.png` would
// be loaded by the browser (tracker beacon, or XSS via SVG content-type).
//
// VITE_ATTACHMENT_ALLOWED_ORIGINS is an optional comma-separated list for
// deployments that legitimately serve attachments from a CDN distinct from the
// API origin (e.g. Azure Blob front-door).
const _EXTRA_ALLOWED: string[] = (import.meta.env.VITE_ATTACHMENT_ALLOWED_ORIGINS || "")
  .split(",")
  .map((s: string) => s.trim())
  .filter(Boolean);

function _originOf(url: string): string | null {
  try {
    return new URL(url).origin;
  } catch {
    return null;
  }
}

const ATTACHMENT_ALLOWED_ORIGINS: Set<string> = new Set<string>(
  [_originOf(API_BASE), ..._EXTRA_ALLOWED].filter((s): s is string => !!s),
);

export function isAllowedAttachmentUrl(url: string): boolean {
  if (!url) return false;
  // Optimistic local previews from a freshly picked file: blob: URLs are
  // generated by the browser itself and only resolve in this tab.
  if (url.startsWith("blob:")) return true;
  // Relative API paths like /api/uploads/xxx.png are served by our own
  // backend (which already validates the filename — see api/chat.py
  // serve_upload / serve_output).
  if (url.startsWith("/")) return true;
  // Absolute URL: only allow the explicit origin set above. data: and
  // javascript: URIs are rejected — SVG via data: can carry XSS payloads.
  const origin = _originOf(url);
  if (!origin) return false;
  return ATTACHMENT_ALLOWED_ORIGINS.has(origin);
}

export function resolveAttachmentUrl(url: string): string | null {
  if (!isAllowedAttachmentUrl(url)) return null;
  if (url.startsWith("blob:") || url.startsWith("http://") || url.startsWith("https://")) {
    return url;
  }
  return `${API_BASE}${url}`;
}

interface Props {
  message: Message;
  toolCalls: ToolCallDisplay[];
  toolResultMap: Map<string, string>;
  onToggleToolCall: (call_id: string) => void;
}

export const MessageBubble = memo(function MessageBubble({ message, toolCalls, toolResultMap, onToggleToolCall }: Props) {
  // Local expanded state for historical tool calls (not in the live store)
  const [localExpanded, setLocalExpanded] = useState<Record<string, boolean>>({});
  const [lightboxUrl, setLightboxUrl] = useState<string | null>(null);

  // Parse attachments once
  const attachments: Attachment[] = useMemo(() => {
    if (!message.attachments_json) return [];
    try {
      return JSON.parse(message.attachments_json);
    } catch {
      return [];
    }
  }, [message.attachments_json]);

  if (message.role === "tool") {
    return null;
  }

  const isUser = message.role === "user";

  // Find tool calls for this assistant message. ask_user calls are split out
  // so they can render as natural dialogue (question card) instead of as a
  // generic tool-call card.
  let messageTCs: ToolCallDisplay[] = [];
  let askUserCalls: Array<{ call_id: string; question: QuestionInfo; answers?: QuestionAnswerEntry[] }> = [];
  if (message.role === "assistant" && message.tool_calls_json) {
    try {
      const calls = JSON.parse(message.tool_calls_json) as Array<{
        id: string;
        function: { name: string; arguments: string };
      }>;
      for (const c of calls) {
        const args = (() => {
          try { return JSON.parse(c.function.arguments || "{}"); }
          catch { return {}; }
        })();

        if (c.function.name === "ask_user" && Array.isArray(args.questions)) {
          // Pull answers from the corresponding tool result, if present.
          let answers: QuestionAnswerEntry[] | undefined;
          const raw = toolResultMap.get(c.id);
          if (raw) {
            try {
              // The orchestrator wraps tool results in an envelope:
              //   { status, tool, data: <stringified-or-parsed JSON> }
              // For ask_user, data is a JSON string of { status, answers } or
              // already-parsed object depending on how the envelope was built.
              const envelope = JSON.parse(raw);
              const inner = envelope?.data;
              const parsed = typeof inner === "string" ? JSON.parse(inner) : inner;
              if (parsed && Array.isArray(parsed.answers)) {
                answers = parsed.answers as QuestionAnswerEntry[];
              }
            } catch { /* leave answers undefined */ }
          }

          askUserCalls.push({
            call_id: c.id,
            question: {
              question_id: "", // historical - no live wait
              call_id: c.id,
              questions: args.questions,
            },
            answers,
          });
          continue;
        }

        // Regular tool call
        const existing = toolCalls.find((tc) => tc.call_id === c.id);
        if (existing) {
          messageTCs.push(existing);
        } else {
          messageTCs.push({
            call_id: c.id,
            name: c.function.name,
            args,
            result: toolResultMap.get(c.id),
            expanded: !!localExpanded[c.id],
          });
        }
      }
    } catch {
      // Ignore parse errors
    }
  }

  const handleToggle = (callId: string) => {
    // If it's a live streaming tool call, use store toggle
    const isLive = toolCalls.some((tc) => tc.call_id === callId);
    if (isLive) {
      onToggleToolCall(callId);
    } else {
      // Historical: toggle locally
      setLocalExpanded((prev) => ({ ...prev, [callId]: !prev[callId] }));
    }
  };

  // Only animate freshly-arrived messages. When a user switches conversations
  // we rehydrate full history; without this gate every historical bubble would
  // re-run fade-up simultaneously, which reads as a janky re-render.
  const isFresh = (() => {
    if (!message.created_at) return true;
    const t = new Date(message.created_at).getTime();
    if (!Number.isFinite(t)) return true;
    return Date.now() - t < 5000;
  })();

  return (
    <div className={`flex ${isUser ? "justify-end" : "justify-start"} gap-3 ${isFresh ? "animate-fade-in-up" : ""}`}>
      {!isUser && (
        <div className="w-7 h-7 rounded-lg bg-accent/15 flex items-center justify-center flex-shrink-0 mt-1">
          <Bot className="w-3.5 h-3.5 text-accent-light" />
        </div>
      )}

      <div className={`max-w-[80%] space-y-2`}>
        {message.content && (
          <div
            className={`rounded-xl px-4 py-3 ${
              isUser
                ? "bg-accent text-white text-sm leading-relaxed whitespace-pre-wrap"
                : "bg-base-800/80 text-base-100 prose prose-invert prose-sm prose-chat max-w-none"
            }`}
          >
            {isUser ? (
              message.content
            ) : (
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {message.content}
              </ReactMarkdown>
            )}
          </div>
        )}

        {/* Attachments (images) */}
        {attachments.length > 0 && (
          <div className={`flex flex-wrap gap-2 ${!message.content ? "" : ""}`}>
            {attachments.map((att, i) => {
              const resolved = resolveAttachmentUrl(att.url);
              if (!resolved) {
                // Disallowed origin — render the raw URL as inert text so the
                // user can still inspect it without the browser fetching it.
                return (
                  <div
                    key={att.filename || i}
                    className="text-xs text-base-400 italic px-2 py-1 rounded border border-base-700/40 break-all"
                    title="Attachment from disallowed origin"
                  >
                    Attachment blocked: {att.url}
                  </div>
                );
              }
              return (
                <button
                  key={att.filename || i}
                  onClick={() => setLightboxUrl(resolved)}
                  className="block rounded-lg overflow-hidden border border-base-700/40 hover:border-accent/50 transition-colors duration-150"
                >
                  <img
                    src={resolved}
                    alt={att.original_name || att.filename}
                    className="max-w-[240px] max-h-[180px] object-contain bg-base-900"
                    loading="lazy"
                  />
                </button>
              );
            })}
          </div>
        )}

        {messageTCs.map((tc) => (
          <ToolCallCard key={tc.call_id} tc={tc} onToggle={handleToggle} />
        ))}

        {/* Historical ask_user calls render as a frozen question card so the
            conversation reads as natural Q&A dialogue, not as a tool log. */}
        {askUserCalls.map((c) => (
          <QuestionCard
            key={`ask-${c.call_id}`}
            question={c.question}
            resolved={c.answers}
          />
        ))}
      </div>

      {isUser && (
        <div className="w-7 h-7 rounded-lg bg-base-700/60 flex items-center justify-center flex-shrink-0 mt-1">
          <User className="w-3.5 h-3.5 text-base-400" />
        </div>
      )}

      {/* Lightbox */}
      {lightboxUrl && (
        <Lightbox url={lightboxUrl} onClose={() => setLightboxUrl(null)} />
      )}
    </div>
  );
});

function Lightbox({ url, onClose }: { url: string; onClose: () => void }) {
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Image preview"
      className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center cursor-pointer"
      onClick={onClose}
    >
      <button
        type="button"
        onClick={(e) => {
          e.stopPropagation();
          onClose();
        }}
        aria-label="Close preview"
        title="Close (Esc)"
        className="absolute top-4 right-4 w-10 h-10 rounded-full bg-base-900/80 hover:bg-base-800 border border-base-700/60 hover:border-base-600 text-base-100 flex items-center justify-center transition-colors duration-150"
      >
        <X className="w-5 h-5" />
      </button>
      <img
        src={url}
        alt="Preview"
        className="max-w-[90vw] max-h-[90vh] object-contain rounded-lg"
        onClick={(e) => e.stopPropagation()}
      />
    </div>
  );
}
