"""Offline generator for app/diagram_ir/_font_advances.py.

draw.io renders labels in Helvetica, which Windows/Chromium substitutes with
Arial — so Arial's advance widths ARE the pixels a viewer sees. This script
extracts per-character advances (font units, unitsPerEm-normalized at use
time) from the system Arial regular + bold faces and bakes them into a
committed Python module, so runtime text measurement is exact, deterministic,
and dependency-free.

Run once (or when the character set changes):

    pip install fonttools
    python scripts/gen_font_advances.py

Requires C:\\Windows\\Fonts\\arial.ttf and arialbd.ttf (any Windows box) or an
Arial-metric-compatible face (Liberation Sans) — pass paths as argv[1]/[2].
"""

from __future__ import annotations

import sys
from pathlib import Path

from fontTools.ttLib import TTFont

# ASCII printable + Latin-1 letters + the typographic characters that show up
# in real diagram labels (arrows, dashes, quotes, ellipsis, bullets).
_CODEPOINTS = (
    list(range(0x20, 0x7F))
    + list(range(0xA0, 0x100))
    + [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x2192, 0x2194]
)

_OUT = Path(__file__).resolve().parents[1] / "app" / "diagram_ir" / "_font_advances.py"


def _advances(font_path: str) -> tuple[int, dict[str, int]]:
    font = TTFont(font_path)
    upem = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    table = {}
    for cp in _CODEPOINTS:
        glyph = cmap.get(cp)
        if glyph is not None:
            table[chr(cp)] = hmtx[glyph][0]
    return upem, table


def _fmt(table: dict[str, int]) -> str:
    items = ", ".join(f"{ch!r}: {adv}" for ch, adv in sorted(table.items()))
    return "{" + items + "}"


def main() -> None:
    reg_path = sys.argv[1] if len(sys.argv) > 1 else r"C:\Windows\Fonts\arial.ttf"
    bold_path = sys.argv[2] if len(sys.argv) > 2 else r"C:\Windows\Fonts\arialbd.ttf"
    upem, reg = _advances(reg_path)
    upem_b, bold = _advances(bold_path)
    if upem != upem_b:
        raise SystemExit(f"unitsPerEm mismatch: regular={upem} bold={upem_b}")

    _OUT.write_text(
        '"""Arial advance widths in font units (auto-generated — do not edit).\n\n'
        "Generated by scripts/gen_font_advances.py; see that script for why Arial\n"
        'is the right metrics source for draw.io output. Used by textmetrics.py.\n"""\n\n'
        f"UPEM = {upem}\n\n"
        f"ADV_REGULAR = {_fmt(reg)}\n\n"
        f"ADV_BOLD = {_fmt(bold)}\n",
        encoding="utf-8",
    )
    print(f"wrote {_OUT} ({len(reg)} regular / {len(bold)} bold glyphs, upem={upem})")


if __name__ == "__main__":
    main()
