"""
Generate a pixel-faithful, Microsoft-reference-style architecture diagram from a
structural **Diagram IR** (containment + tokens, no coordinates).

This is the third diagram path, distinct from the other two:

  * `generate_python_diagram`        — Graphviz auto-layout of a free graph
                                       (branching flowcharts, "autogenerated" look)
  * `generate_drawio_from_python`    — hand-placed / per-cell drawio authoring
  * `generate_structured_diagram`    — THIS: containment-canonical cloud topology
                                       (VNet ▸ subnet ▸ resource, multi-AZ tiers)
                                       laid out + routed deterministically into the
                                       Microsoft reference look.

You describe *structure only* — nested containers, leaf nodes with provider icons,
edges with semantic types, and per-container `layout` hints. The engine computes
all geometry, places Azure2/AWS4 icons, draws corner adornments, and routes
connectors around icons (no manual pixel coordinates). The result is a `.drawio`
plus an auto-rendered PNG in output/.

Pipeline: JSON IR → schema-load → validate (hard gate) → layout → route → emit →
render. A broken IR (bad token, dangling parent/edge, id clash) is rejected with a
precise message before anything is drawn; advisory warnings (empty/isolated/
duplicate) are reported but do not block.
"""

import logging
import re
from pathlib import Path

from app.auth.models import User
from app.diagram_ir.emit import emit_drawio
from app.diagram_ir.geometry import check_edge_crossings, check_edge_overlaps
from app.diagram_ir.layout import layout_diagram
from app.diagram_ir.loader import IRSchemaError, load_ir
from app.diagram_ir.routing import route_edges_gutter
from app.diagram_ir.validate import validate_ir
from app.tools.base import Tool
from app.tools.generic.render_drawio import render_drawio_to_disk

logger = logging.getLogger(__name__)

_OUTPUT_DIR = Path("output")
_FILENAME_RE = re.compile(r"^[A-Za-z0-9_\-]+$")

# Per-box schema reused for both nodes and containers (function-calling schemas
# can't share $defs cleanly across providers, so we inline the common shape).
_ADORNMENT_SCHEMA = {
    "type": "object",
    "description": "A fixed-corner glyph on a box (e.g. an NSG badge on a subnet, a WAF badge on a gateway).",
    "properties": {
        "icon": {"type": "string", "description": "Icon ref, e.g. 'azure/network_security_groups', 'aws/waf'."},
        "corner": {"type": "string", "enum": ["top-left", "top-right", "bottom-left", "bottom-right"]},
        "label": {"type": "string"},
    },
    "required": ["icon"],
}


class GenerateStructuredDiagramTool(Tool):
    name = "generate_structured_diagram"
    config_flag = "TOOL_STRUCTURED_DIAGRAM_ENABLED"
    is_diagram_tool = True          # strip echoed XML if the result is truncated
    learning_eligible = True
    description = (
        "Render a Microsoft-reference-style cloud architecture diagram from a "
        "structural Diagram IR (containment + style/layout tokens, NO pixel "
        "coordinates). Best for containment-canonical topologies: a VNet/VPC "
        "with nested subnets and resources, multi-AZ tiers, monitoring/identity "
        "zones, satellite services. The engine computes every coordinate, places "
        "Azure2/AWS4 icons, and routes connectors around icons automatically — "
        "you only declare the structure.\n\n"
        "Choose this over generate_python_diagram when you need the polished, "
        "grid-aligned Microsoft look (nested dashed VNet boxes, subnet bands) "
        "rather than Graphviz auto-layout; choose generate_python_diagram for "
        "branching flowcharts where the shape comes from edges, not containment.\n\n"
        "IR shape (pass as the `diagram` object):\n"
        "  - containers[]: {id, label, style, parent?, children[], layout?, "
        "grid_cols?, align_to?, adornments[]}\n"
        "      style ∈ vnet|vpc|subnet|resource_group|zone|monitoring|group|band "
        "(band = invisible layout-only grouping)\n"
        "      layout ∈ row|column|grid ('' = row for LR / column for TB)\n"
        "      align_to = id of a box this one should sit over (a satellite "
        "service above the resource it serves) — a hint, never inferred from edges\n"
        "  - nodes[]: {id, label, icon, parent?, align_to?, adornments[]}\n"
        "      icon = '<provider>/<name>', e.g. 'azure/app_services', 'aws/ecs', "
        "or 'shape/<builtin>' (cloud, cylinder, process, decision, ...)\n"
        "  - edges[]: {source, target, type?, label?}  "
        "type ∈ flow|private|dns|telemetry|replication\n"
        "  - direction ∈ LR|TB (default LR), title\n\n"
        "Use invisible 'band' containers with layout=row/column to express 2D "
        "arrangements a single-axis flow can't (e.g. a satellite row over the "
        "main flow). Every container needs its children listed AND each child's "
        "parent set to that container (they must agree). A broken IR is rejected "
        "with a precise error; fix and retry with the same filename to overwrite."
    )
    parameters_schema = {
        "type": "object",
        "properties": {
            "filename": {
                "type": "string",
                "description": (
                    "Output filename stem (no extension). Letters, digits, "
                    "underscore, hyphen only. Writes output/<filename>.drawio and "
                    "output/<filename>.png."
                ),
            },
            "diagram": {
                "type": "object",
                "description": "The structural Diagram IR.",
                "properties": {
                    "title": {"type": "string"},
                    "direction": {"type": "string", "enum": ["LR", "TB"]},
                    "containers": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "string"},
                                "label": {"type": "string"},
                                "style": {
                                    "type": "string",
                                    "enum": ["vnet", "vpc", "subnet", "resource_group",
                                             "zone", "monitoring", "group", "band"],
                                },
                                "parent": {"type": "string"},
                                "children": {"type": "array", "items": {"type": "string"}},
                                "layout": {"type": "string", "enum": ["", "row", "column", "grid"]},
                                "grid_cols": {"type": "integer"},
                                "align_to": {"type": "string"},
                                "adornments": {"type": "array", "items": _ADORNMENT_SCHEMA},
                            },
                            "required": ["id", "style"],
                        },
                    },
                    "nodes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "string"},
                                "label": {"type": "string"},
                                "icon": {"type": "string"},
                                "parent": {"type": "string"},
                                "align_to": {"type": "string"},
                                "adornments": {"type": "array", "items": _ADORNMENT_SCHEMA},
                            },
                            "required": ["id", "icon"],
                        },
                    },
                    "edges": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "source": {"type": "string"},
                                "target": {"type": "string"},
                                "type": {
                                    "type": "string",
                                    "enum": ["flow", "private", "dns", "telemetry", "replication"],
                                },
                                "label": {"type": "string"},
                            },
                            "required": ["source", "target"],
                        },
                    },
                },
            },
        },
        "required": ["filename", "diagram"],
    }
    requires_approval = False

    def execute(self, args: dict, user: User) -> str:
        if not isinstance(args, dict):
            return "Error: invalid arguments - expected an object with filename and diagram"

        filename = (args.get("filename") or args.get("name") or "").strip()
        if not filename:
            return "Error: filename is required"
        stem = Path(filename).stem
        if not _FILENAME_RE.match(stem):
            return (
                "Error: filename may only contain letters, digits, underscore, and "
                "hyphen (no spaces, paths, or extensions)."
            )

        ir = args.get("diagram")
        if isinstance(ir, str):
            import json
            try:
                ir = json.loads(ir)
            except json.JSONDecodeError as e:
                return f"Error: `diagram` was a string but not valid JSON: {e}"
        if not isinstance(ir, dict):
            return "Error: `diagram` is required and must be the IR object (containers/nodes/edges)."

        # Stage 1 — schema load (precise field-level errors).
        try:
            diagram = load_ir(ir)
        except IRSchemaError as e:
            return f"Error: Diagram IR schema invalid - {e}"

        # Stage 2 — hard validation gate. Render nothing on a structurally broken IR.
        v = validate_ir(diagram)
        if not v.ok:
            return (
                "Error: Diagram IR rejected by the validator (fix and retry):\n"
                f"{v.report()}"
            )
        warnings_note = ""
        if v.warnings:
            warnings_note = "\nValidator warnings (did not block):\n" + "\n".join(
                f"  - {w}" for w in v.warnings
            )

        # Stage 3 — layout + route + emit (all deterministic, geometry computed).
        try:
            layout_diagram(diagram)
            routes = route_edges_gutter(diagram)
            xml = emit_drawio(diagram, routes=routes)
        except Exception as e:  # engine bug, not user error — surface it
            logger.exception("Structured diagram engine failed for %s", user.email)
            return f"Error: layout/route/emit failed unexpectedly: {e}"

        # Stage 4 — write the .drawio.
        sandbox = _OUTPUT_DIR.resolve()
        sandbox.mkdir(parents=True, exist_ok=True)
        drawio_path = sandbox / f"{stem}.drawio"
        try:
            drawio_path.write_text(xml, encoding="utf-8")
        except OSError as e:
            return f"Error writing {stem}.drawio: {e}"

        # Stage 5 — scorecard (A = line over icon, C = arrow hidden behind arrow).
        a = check_edge_crossings(diagram, routes)
        c = check_edge_overlaps(diagram, routes)
        score = f"layout scorecard: A(line-over-icon)={len(a)}  C(arrow-hidden)={len(c)}"
        score_detail = ""
        if a or c:
            score_detail = "\n" + "\n".join(f"  - {m}" for m in (*a, *c))

        # Stage 6 — render to PNG (reuses the sidecar/CLI pipeline; non-fatal on failure).
        out_path, mode, err = render_drawio_to_disk(f"{stem}.drawio", "png")
        if err is not None or out_path is None:
            return (
                f"Diagram IR validated and written: output/{stem}.drawio\n"
                f"{score}{score_detail}{warnings_note}\n\n"
                f"NOTE: PNG render failed — the .drawio is valid and openable, but "
                f"no image preview was produced: {err}"
            )

        size_kb = out_path.stat().st_size // 1024
        logger.info(
            "Rendered structured diagram: %s.png (%d KB, A=%d C=%d) via %s for %s",
            stem, size_kb, len(a), len(c), mode, user.email,
        )
        return (
            f"Diagram rendered: output/{out_path.name} ({size_kb} KB, via {mode})\n"
            f"Source: output/{stem}.drawio\n"
            f"{score}{score_detail}{warnings_note}\n\n"
            "The rendered image is being attached to your next turn for visual "
            "review. Inspect it and check:\n"
            "  - Container nesting matches the architecture (subnets inside the VNet, etc.)\n"
            "  - No label is clipped and icons sit centered under their labels\n"
            "  - Satellite services sit over the element they relate to (use align_to if not)\n"
            "  - Edges connect the right nodes with sensible routing\n\n"
            "If something is wrong, adjust the IR and re-run with the same filename "
            "(it overwrites). A non-zero A or C above means a connector crosses an "
            "icon or hides behind another — usually fixed by spreading nodes or "
            "adding an invisible 'band' to change the arrangement."
        )
