"""
Generate a pixel-faithful, Microsoft-reference-style architecture diagram from a
structural **Diagram IR** (containment + tokens, no coordinates).

This is the third diagram path, distinct from the other two:

  * `generate_python_diagram`        — Graphviz auto-layout of a free graph
                                       (branching flowcharts, "autogenerated" look)
  * `generate_drawio_from_python`    — hand-placed / per-cell drawio authoring
  * `generate_structured_diagram`    — THIS: containment-canonical cloud topology
                                       (VNet ▸ subnet ▸ resource, multi-AZ tiers)
                                       laid out + routed deterministically into the
                                       Microsoft reference look.

You describe *structure only* — nested containers, leaf nodes with provider icons,
edges with semantic types, and per-container `layout` hints. The engine computes
all geometry, places Azure2/AWS4 icons, draws corner adornments, and routes
connectors around icons (no manual pixel coordinates). The result is a `.drawio`
plus an auto-rendered PNG in output/.

Pipeline: JSON IR → schema-load → validate (hard gate) → layout → route → emit →
render. A broken IR (bad token, dangling parent/edge, id clash) is rejected with a
precise message before anything is drawn; advisory warnings (empty/isolated/
duplicate) are reported but do not block.
"""

import logging
import re
from pathlib import Path

from app.auth.models import User
from app.diagram_ir.emit import emit_drawio
from app.diagram_ir.geometry import (
    check_edge_crossings,
    check_edge_overlaps,
    check_flow_placement,
    check_label_collisions,
    check_line_over_labels,
)
from app.diagram_ir.labels import place_edge_labels
from app.diagram_ir.layout import layout_diagram
from app.diagram_ir.loader import IRSchemaError, load_ir
from app.diagram_ir.routing import route_edges_gutter
from app.diagram_ir.validate import validate_ir
from app.tools.base import Tool
from app.tools.generic.render_drawio import render_drawio_to_disk

logger = logging.getLogger(__name__)

_OUTPUT_DIR = Path("output")
_FILENAME_RE = re.compile(r"^[A-Za-z0-9_\-]+$")

# Per-box schema reused for both nodes and containers (function-calling schemas
# can't share $defs cleanly across providers, so we inline the common shape).
_ADORNMENT_SCHEMA = {
    "type": "object",
    "description": "A fixed-corner glyph on a box (e.g. an NSG badge on a subnet, a WAF badge on a gateway).",
    "properties": {
        "icon": {"type": "string", "description": "Icon ref, e.g. 'azure/network_security_groups', 'aws/waf'."},
        "corner": {"type": "string", "enum": ["top-left", "top-right", "bottom-left", "bottom-right"]},
        "label": {"type": "string"},
    },
    "required": ["icon"],
}


class GenerateStructuredDiagramTool(Tool):
    name = "generate_structured_diagram"
    config_flag = "TOOL_STRUCTURED_DIAGRAM_ENABLED"
    is_diagram_tool = True          # strip echoed XML if the result is truncated
    attaches_render = True   # fresh PNG on success - orchestrator attaches + vision-reviews
    learning_eligible = True
    description = (
        "Render a Microsoft-reference-style cloud architecture diagram from a "
        "structural Diagram IR (containment + style/layout tokens, NO pixel "
        "coordinates). Best for containment-canonical topologies: a VNet/VPC "
        "with nested subnets and resources, multi-AZ tiers, monitoring/identity "
        "zones, satellite services. The engine computes every coordinate, places "
        "Azure2/AWS4 icons, and routes connectors around icons automatically — "
        "you only declare the structure.\n\n"
        "Choose this over generate_python_diagram when you need the polished, "
        "grid-aligned Microsoft look (nested dashed VNet boxes, subnet bands) "
        "rather than Graphviz auto-layout; choose generate_python_diagram for "
        "branching flowcharts where the shape comes from edges, not containment.\n\n"
        "IR shape (pass as the `diagram` object):\n"
        "  - containers[]: {id, label, style, parent?, children[], layout?, "
        "grid_cols?, align_to?, adornments[]}\n"
        "      style ∈ vnet|vpc|subnet|resource_group|zone|monitoring|group|band "
        "(band = invisible layout-only grouping)\n"
        "      layout ∈ row|column|grid ('' = row for LR / column for TB)\n"
        "      align_to = id of a box this one should sit over (a satellite "
        "service above the resource it serves) — a hint, never inferred from edges\n"
        "  - nodes[]: {id, label, icon, parent?, align_to?, adornments[]}\n"
        "      icon = '<provider>/<name>', e.g. 'azure/app_services', 'aws/ecs', "
        "or 'shape/<builtin>' (cloud, cylinder, process, decision, ...)\n"
        "  - edges[]: {source, target, type?, label?}  "
        "type ∈ flow|private|dns|telemetry|replication\n"
        "  - direction ∈ LR|TB (default LR), title\n\n"
        "Edge-label discipline: labels are placed deterministically to avoid "
        "collisions, but fewer/shorter is always better. Keep labels ≤3 words and "
        "factual ('HTTPS', 'API calls') — never hedging ('likely main path'). OMIT "
        "the label when the edge type already conveys it (private/dns/telemetry "
        "render as distinct dashed styles), and never draw an edge that restates "
        "containment (a private endpoint inside a subnet needs no 'private "
        "placement' arrow).\n\n"
        "Layout doctrine (what makes it read like a reference architecture): give "
        "the flow a head and a tail — the OUTER container's layout runs WITH "
        "direction (row for LR, column for TB), children ordered by traffic "
        "position, each stage a cross-axis cluster; commit to one axis, no "
        "hybrids. ORDER STAGES BY TRAFFIC POSITION, NOT CATEGORY: the container "
        "hosting hop N of the flow sits between the stages hosting hops N-1 and "
        "N+1 — e.g. a VNet whose subnet holds an internal APIM (hop 3) is a "
        "MIDDLE stage between the web tier and the API tier, never a "
        "'networking' block parked at the end (that turns every hop through it "
        "into a canvas-crossing round trip). If one stage's members sit at very "
        "different flow positions (web=hop 2, database=hop 6), SPLIT it into "
        "two stages. Put the most-connected hub in the middle of its tier so "
        "straight connectors radiate. For 2D inside a stage, nest invisible "
        "'band' containers (a satellite row over the main flow = a column band "
        "of two row bands). align_to is for a satellite in ANOTHER band only — "
        "a same-band align_to is ignored with a warning.\n\n"
        "Icon catalog — azure/: front_doors, application_gateways, firewalls, "
        "load_balancers, nat_gateway, virtual_networks, virtual_network_gateways, "
        "expressroute, network_security_groups, private_endpoint, private_link, "
        "dns_private_zones, dns_zones, public_ip_addresses, bastions, "
        "route_tables, subnet, web_application_firewall, app_services, "
        "app_service_plans, function_apps, virtual_machine, vm_scale_sets, "
        "kubernetes_services (aks), container_registries (acr), "
        "container_instances, container_apps, sql_database, sql_managed_instance, "
        "cosmos_db, redis, postgresql, mysql, storage_accounts, blob, entra_id, "
        "managed_identities, key_vaults, defender, sentinel, monitor, "
        "log_analytics, application_insights, policy, api_management (apim), "
        "logic_apps, service_bus, event_grid, event_hubs, app_configuration, "
        "openai, cognitive_services, ai_search, machine_learning. "
        "aws/: route_53, cloudfront, waf, application_load_balancer, nat_gateway, "
        "vpc, api_gateway, ecs, eks, lambda, ec2, aurora, rds, dynamodb, "
        "elasticache, s3, secrets_manager, iam. "
        "shape/ (non-branded only): cloud, cylinder, process, subprocess, "
        "decision, terminator, document, datastore, queue, actor. "
        "Always use the real azure/aws icon for a branded service; if one is "
        "truly missing, use the closest match or a shape/* fallback and tell the "
        "user. Unknown refs are rejected with close-match suggestions.\n\n"
        "Every container lists its children AND each child's parent points back "
        "(they must agree); style may be omitted (inferred: subnet inside "
        "vnet/vpc, else group). A broken IR is rejected with a precise error; "
        "fix and retry with the same filename to overwrite.\n\n"
        "Iteration contract: pass the full `diagram` on the FIRST call only. "
        "Every later change goes through `edits` (small delta ops against the "
        "stored IR of the last render) — never re-send the whole diagram. The "
        "result's 'Structure' echo is the authoritative list of what the "
        "diagram contains; judge presence/absence from it, not from the image."
    )
    parameters_schema = {
        "type": "object",
        "properties": {
            "filename": {
                "type": "string",
                "description": (
                    "Output filename stem (no extension). Letters, digits, "
                    "underscore, hyphen only. Writes output/<filename>.drawio and "
                    "output/<filename>.png."
                ),
            },
            "edits": {
                "type": "array",
                "description": (
                    "Incremental changes to the LAST successfully rendered IR for "
                    "this filename (stored server-side). STRONGLY preferred over "
                    "re-sending `diagram` after the first render — re-emitting the "
                    "full IR from memory is how nodes silently get lost between "
                    "iterations. Parent/children stay in sync automatically. Ops: "
                    "{op:'set', title?, direction?} | "
                    "{op:'upsert_node', node:{id,...}} | {op:'remove_node', id} | "
                    "{op:'upsert_container', container:{id,...}} (children, when "
                    "given, REPLACES the list and re-parents; may name ids a "
                    "later op in the SAME batch creates) | "
                    "{op:'remove_container', id} (dissolves: children re-parent "
                    "to its parent automatically) | "
                    "{op:'upsert_edge', edge:{source,target,type?,label?}} | "
                    "{op:'remove_edge', source, target}"
                ),
                "items": {
                    "type": "object",
                    "properties": {
                        "op": {"type": "string",
                               "enum": ["set", "upsert_node", "remove_node",
                                        "upsert_container", "remove_container",
                                        "upsert_edge", "remove_edge"]},
                        "node": {"type": "object"},
                        "container": {"type": "object"},
                        "edge": {"type": "object"},
                        "id": {"type": "string"},
                        "source": {"type": "string"},
                        "target": {"type": "string"},
                        "title": {"type": "string"},
                        "direction": {"type": "string", "enum": ["LR", "TB"]},
                    },
                    "required": ["op"],
                },
            },
            "diagram": {
                "type": "object",
                "description": (
                    "The full structural Diagram IR. Required on the FIRST call "
                    "for a filename; on every later call prefer `edits`."
                ),
                "properties": {
                    "title": {"type": "string"},
                    "direction": {"type": "string", "enum": ["LR", "TB"]},
                    "containers": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "string"},
                                "label": {"type": "string"},
                                "style": {
                                    "type": "string",
                                    "enum": ["vnet", "vpc", "subnet", "resource_group",
                                             "zone", "monitoring", "group", "band"],
                                },
                                "parent": {"type": "string"},
                                "children": {"type": "array", "items": {"type": "string"}},
                                "layout": {"type": "string", "enum": ["", "row", "column", "grid"]},
                                "grid_cols": {"type": "integer"},
                                "align_to": {"type": "string"},
                                "adornments": {"type": "array", "items": _ADORNMENT_SCHEMA},
                            },
                            "required": ["id", "style"],
                        },
                    },
                    "nodes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "string"},
                                "label": {"type": "string"},
                                "icon": {"type": "string"},
                                "parent": {"type": "string"},
                                "align_to": {"type": "string"},
                                "adornments": {"type": "array", "items": _ADORNMENT_SCHEMA},
                            },
                            "required": ["id", "icon"],
                        },
                    },
                    "edges": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "source": {"type": "string"},
                                "target": {"type": "string"},
                                "type": {
                                    "type": "string",
                                    "enum": ["flow", "private", "dns", "telemetry", "replication"],
                                },
                                "label": {"type": "string"},
                            },
                            "required": ["source", "target"],
                        },
                    },
                },
            },
        },
        "required": ["filename"],
    }
    requires_approval = False

    def execute(self, args: dict, user: User) -> str:
        import json

        if not isinstance(args, dict):
            return "Error: invalid arguments - expected an object with filename and diagram/edits"

        filename = (args.get("filename") or args.get("name") or "").strip()
        if not filename:
            return "Error: filename is required"
        stem = Path(filename).stem
        if not _FILENAME_RE.match(stem):
            return (
                "Error: filename may only contain letters, digits, underscore, and "
                "hyphen (no spaces, paths, or extensions)."
            )

        ir = args.get("diagram")
        if isinstance(ir, str):
            try:
                ir = json.loads(ir)
            except json.JSONDecodeError as e:
                return f"Error: `diagram` was a string but not valid JSON: {e}"

        edits = args.get("edits")
        sidecar = (_OUTPUT_DIR / f"{stem}.ir.json").resolve()
        if not isinstance(ir, dict):
            if edits:
                # Edits-only call: base is the IR of the last successful render.
                if not sidecar.is_file():
                    return (
                        f"Error: no stored IR for '{stem}' — the first call for a "
                        "filename must pass the full `diagram`; `edits` works from "
                        "the second call on."
                    )
                try:
                    ir = json.loads(sidecar.read_text(encoding="utf-8"))
                except (OSError, json.JSONDecodeError) as e:
                    return f"Error: stored IR for '{stem}' unreadable ({e}) — pass the full `diagram`."
            else:
                return (
                    "Error: pass `diagram` (the full IR — first call) or `edits` "
                    "(changes to the stored IR — every later call)."
                )
        if edits:
            from app.diagram_ir.edits import apply_edits
            ir, edit_err = apply_edits(ir, edits)
            if edit_err is not None:
                return f"Error: {edit_err}"

        # Stage 1 — schema load (precise field-level errors).
        try:
            diagram = load_ir(ir)
        except IRSchemaError as e:
            return f"Error: Diagram IR schema invalid - {e}"

        # Stage 2 — hard validation gate. Render nothing on a structurally broken IR.
        v = validate_ir(diagram)
        if not v.ok:
            return (
                "Error: Diagram IR rejected by the validator (fix and retry):\n"
                f"{v.report()}"
            )
        warnings_note = ""
        if v.warnings:
            warnings_note = "\nValidator warnings (did not block):\n" + "\n".join(
                f"  - {w}" for w in v.warnings
            )

        # Stage 3 — layout + route + place labels + emit (all deterministic).
        # Text-aware auto-iteration: when the first pass leaves a line through
        # label text (B) or a label collision (D), retry routing once with
        # more obstacle clearance and keep whichever pass scores fewer total
        # defects — engine CPU instead of a chat round-trip + vision review.
        try:
            layout_diagram(diagram)
            routes = route_edges_gutter(diagram)
            place_edge_labels(diagram, routes)
            a = check_edge_crossings(diagram, routes)
            b = check_line_over_labels(diagram, routes)
            c = check_edge_overlaps(diagram, routes)
            d = check_label_collisions(diagram, routes)
            if b or d:
                routes2 = route_edges_gutter(diagram, clearance=18.0)
                place_edge_labels(diagram, routes2)
                a2 = check_edge_crossings(diagram, routes2)
                b2 = check_line_over_labels(diagram, routes2)
                c2 = check_edge_overlaps(diagram, routes2)
                d2 = check_label_collisions(diagram, routes2)
                if len(a2) + len(b2) + len(c2) + len(d2) < len(a) + len(b) + len(c) + len(d):
                    routes, a, b, c, d = routes2, a2, b2, c2, d2
            xml = emit_drawio(diagram, routes=routes)
        except Exception as e:  # engine bug, not user error — surface it
            logger.exception("Structured diagram engine failed for %s", user.email)
            return f"Error: layout/route/emit failed unexpectedly: {e}"

        # Stage 4 — write the .drawio + persist the accepted IR as the sidecar
        # `edits` works against. The sidecar always matches the .drawio on disk,
        # so an incremental call can never base itself on structure that was
        # never rendered.
        sandbox = _OUTPUT_DIR.resolve()
        sandbox.mkdir(parents=True, exist_ok=True)
        drawio_path = sandbox / f"{stem}.drawio"
        try:
            drawio_path.write_text(xml, encoding="utf-8")
        except OSError as e:
            return f"Error writing {stem}.drawio: {e}"
        try:
            (sandbox / f"{stem}.ir.json").write_text(
                json.dumps(ir, indent=2, ensure_ascii=False), encoding="utf-8",
            )
        except OSError:
            logger.warning("Could not persist IR sidecar for %s", stem)

        # Structural echo — the authoritative answer to "what does the diagram
        # contain". The model must verify presence/absence HERE; the rendered
        # image (small icons, downscaled for vision) is only for visual quality.
        # Conv #352 burned 4 renders chasing nodes the vision pass hallucinated
        # as missing.
        echo = (
            "Structure (authoritative — check presence/absence here, NOT in the image):\n"
            f"  containers ({len(diagram.containers)}): "
            + (", ".join(c.id for c in diagram.containers) or "—") + "\n"
            f"  nodes ({len(diagram.nodes)}): "
            + (", ".join(n.id for n in diagram.nodes) or "—") + "\n"
            f"  edges ({len(diagram.edges)}): "
            + (", ".join(f"{e.source}->{e.target}" for e in diagram.edges) or "—")
        )

        # Stage 5 — scorecard. A/C = icon/arrow defects; B/D = the text defects
        # (line through label text, label on label) that dominated real renders.
        score = (
            f"layout scorecard: A(line-over-icon)={len(a)}  "
            f"B(line-over-label)={len(b)}  C(arrow-hidden)={len(c)}  "
            f"D(label-collision)={len(d)}"
        )
        score_detail = ""
        if a or b or c or d:
            score_detail = "\n" + "\n".join(f"  - {m}" for m in (*a, *b, *c, *d))

        # Placement advisory — consecutive flow hops drawn far apart because a
        # mid-flow component was parked in the wrong stage. The router can't
        # fix authoring; this tells the author (the model) HOW to fix it.
        placement = check_flow_placement(diagram)
        from app.diagram_ir.geometry import check_side_lane
        placement += check_side_lane(diagram)
        if placement:
            score_detail += "\nPlacement advisory (fix via `edits`, then re-render):\n" + \
                "\n".join(f"  - {m}" for m in placement)

        # Stage 6 — render to PNG (reuses the sidecar/CLI pipeline; non-fatal on failure).
        out_path, mode, err = render_drawio_to_disk(f"{stem}.drawio", "png")
        if err is not None or out_path is None:
            return (
                f"Diagram IR validated and written: output/{stem}.drawio\n"
                f"{score}{score_detail}{warnings_note}\n{echo}\n\n"
                f"NOTE: PNG render failed — the .drawio is valid and openable, but "
                f"no image preview was produced: {err}"
            )

        size_kb = out_path.stat().st_size // 1024
        logger.info(
            "Rendered structured diagram: %s.png (%d KB, A=%d B=%d C=%d D=%d) via %s for %s",
            stem, size_kb, len(a), len(b), len(c), len(d), mode, user.email,
        )
        return (
            f"Diagram rendered: output/{out_path.name} ({size_kb} KB, via {mode})\n"
            f"Source: output/{stem}.drawio\n"
            f"{score}{score_detail}{warnings_note}\n{echo}\n\n"
            "The rendered image is attached to your next turn. Review it against "
            "the agreed structure; if something is wrong, fix it with a small "
            "`edits` call against the same filename — do NOT re-send the full "
            "diagram (re-emitting it from memory is how structure gets lost). "
            "Non-zero A/C = a connector crosses an icon or hides behind another "
            "(spread nodes or add a 'band'); non-zero B/D = text problems "
            "(shorten or DROP edge labels first). If it looks right, present it "
            "to the user in one or two sentences."
        )
